language: cpp
cache: apt

env:
  - QT=qt54

branches:
  only:
    - 'master'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libssl-dev pkg-config libhunspell-dev
  - if [[ "$QT" == "qt54" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt541; sudo apt-get update -qq; sudo apt-get install -qq qt54tools qt54script qt54webengine qt54webchannel; fi

script:
  - QMAKE="qmake"
  - if [[ "$QT" == "qt54" ]]; then QMAKE="/opt/qt54/bin/qmake"; fi
  - $QMAKE
#  - $QMAKE QMAKE_CXXFLAGS+="-Wextra -Werror"
  - make || exit 1
#  - cd scripts && ./run_tests.sh $QMAKE
