language: cpp

env:
  - QT=qt4
  - QT=qt5

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libssl-dev pkg-config libhunspell-dev
  - [[ "$QT" == "qt4" ]] && sudo apt-get -qq install libqt4-dev libqt4-webkit libqt4-sql-sqlite
  - [[ "$QT" == "qt5" ]] && sudo apt-get -qq install libqt5-dev

script:
  - [[ "$QT" == "qt5" ]] && alias qmake=`qtchooser -qt=qt5 -run-tool=qmake --help | head -n1 | cut -d" " -f2`
  - qmake
  - make
  - cd scripts && source run_tests.sh
