language: cpp

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libqt4-dev libqt4-webkit libqt4-sql-sqlite libssl-dev pkg-config libhunspell-dev

script:
  - qmake
  - make
  - cd scripts && ./run_tests.sh
