sudo: required
dist: trusty
language: cpp
cache: apt

env:
  - QT=qt57

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev
  - if [[ "$QT" == "qt57" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt57-trusty; sudo apt-get update -qq; sudo apt-get install -qq qt57tools qt57script qt57webengine qt57webchannel qt57declarative qt57x11extras; fi

script:
  - QMAKE="qmake"
  - if [[ "$QT" == "qt57" ]]; then QMAKE="/opt/qt57/bin/qmake"; fi
  - $QMAKE QMAKE_CXXFLAGS+="-Wextra -Werror"
  - make || exit 1
  - cd scripts && ./run_tests.sh $QMAKE
